services:
  - type: web
    name: rashtrsetu-backend
    env: node
    plan: free
    buildCommand: |
      cd Frontend && npm install && npm run build
      cd ../Backend && npm install
    startCommand: node app.js
    rootDir: Backend
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_BASE_URL
        value: https://rashtrsetu-backend.onrender.com
