# render.yaml
services:
  - type: web
    name: rashtrsetu-fullstack
    env: node
    rootDir: Backend
    buildCommand: |
      cd ../Frontend && npm install && npm run build
      cd ../Backend && npm install
    startCommand: node app.js

    startCommand: "node app.js"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGO_URL
        value: "mongodb+srv://Kanishk078:Kanishk%405678@cluster0.jolyzxb.mongodb.net/QA?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "KSRKSRKSRKSRKSR"
      - key: COHERE_API_KEY
        value: "1PK6pCwGJ9Zh9HcucAdbe9rKd2LnJzOj5utP8QVs"
        key: PORT
        Value: 5000


# You can add more env vars if needed
